version: '3.3'

networks:
  ntw_front:
    external: true

configs:
  traefik.toml:
    file: ./configs/traefik.toml

services:

  traefik:
    image: traefik:1.4.0-alpine
    command: --docker \
      --docker.swarmmode \
      --docker.domain=traefik \
      --docker.watch \
      --debug=true \
      --logLevel=WARN \
      --web \
      --web.metrics.prometheus \
      --web.metrics.prometheus.buckets="0.1,0.3,1.2,5.0" \
      --web.address=:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - mode: ingress
        published: 80
        target: 80
      - mode: host
        published: 8080
        target: 8080
    networks:
      - ntw_front
    configs:
      - source: traefik.toml
        target: /etc/traefik/traefik.toml
    deploy:
      #labels:
      #- "traefik.enable=false"
      mode: replicated
      replicas: 1
      update_config:
        delay: 2s
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
        max_attempts: 5
      resources:
        limits:
          cpus: '0.33'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 64M