version: '2'
services:
  proxy:
    image: traefik:v1.4
    command: --web --accessLog --constraints=tag==my-stack
    volumes:
      - /dev/null:/traefik.toml
  server:
    build: ./server
    labels:
      - "traefik.frontend.rule=PathPrefix:/api"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.tags=my-stack"
  frontend:
    build: ./frontend
    labels:
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.tags=my-stack"