version: '2'
services:
  consul:
    image: consul
    command: consul agent -server -dev -client=0.0.0.0 -ui -bootstrap -log-level warn
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"

  reverse-proxy:
    image: reverse-proxy
    command: traefik --consulcatalog.endpoint=consul:8500
    ports:
      - "8080:8080"
      - "80:80"
    depends_on:
      - consul
    links:
      - consul

  registrator:
    depends_on:
      - consul
    image: gliderlabs/registrator:master
    command: -internal consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    links:
      - consul

  home:
    image: abiosoft/caddy
    volumes:
      - ./www/home/srv/:/srv/
    labels:
      - "traefik.backend=home"
      - "traefik.frontend.rule=PathPrefixStrip:/"
      - "traefik.port=2015"
      - "traefik.enable=true"
      - "traefik.backend.loadbalancer.method=drr"
      - "traefik.frontend.entryPoints=http"
      - "traefik.docker.network=ntw_front"
      - "traefik.weight=10"